### ISSUE TITLE
The example 

### ISSUE THREAD

**Issue by rlb222** [jongacnik/kirby-fields-block#3]
After a big struggle I got it to work. Due to my noob-ness it took a while and a lot of trying out with the blueprint.
Maybe you could make it easier on total beginners and add a complete example like this?

Thanks for the plugin!
René

`mypageBlueprint.yml`
```
title: my Page

fields:
  Alinea:    #name of the block
    type: blocks
    fieldsets:
      alinea:
        name: myAlinea
        preview: fields  #this is the important command
        wysiwyg: true
        label: false  
        fields:  #fields that are repeated in this block
          head:
            type: text
          text:
            type: textarea

```
